### ISSUE TITLE
Holes property inside a polygon is still not working even though the option was released.

### ISSUE THREAD

**Issue by junskar** [hansemannn/titanium-googlemaps#113]
Hey!

The holes property is still not working.

My code for the polygon:
var polygon = maps.createPolygon({ points : [[85, -180], [85, 0], [85, 180], [-85, 180], [-85, 0], [-85, -180], [85, -180]], strokeWidth : 0, fillColor : '#48000000', strokeColor : '#48000000', title: 'My Polygon', holes: [ {latitude: 25.774, longitude: -80.190}, {latitude: 18.466, longitude: -66.118}, {latitude: 32.321, longitude: -64.757}, {latitude: 25.774, longitude: -80.190} ], });

This is supposed to create a polygon on whole map with hole in bermuda triangle. Polygon is created but no hole is present. Am i missing something?

Also it would be awesome if it would support [18.466, -66.118] array as "Points" property is supporting.

Would appreciate a lot if this could be fixed.

**Comment by hansemannn** [comment]
Sorry, no resources at this time. Please feel free to submit a PR to fix it.

**Comment by junskar** [comment]
Submitted the pull request with a fix to this issue.

**Comment by hansemannn** [comment]
Thank you, merged!  3.11.1 will be released later today.
