### ISSUE TITLE
 fitBounds Overlays (Circle, Polygon)

### ISSUE THREAD

**Issue by ptsequeira** [hansemannn/titanium-googlemaps#116]
There is a way to fit overlays (Circle and polygon) to map bounds?
I tried **cameUpdate.fitBounds** but only accepts 2 coordinates.

Thanks

**Comment by MattDelmarter** [comment]
I was trying to make a polygon fill the entire map on display, and then use the `holes` in the polygon to show the desired region, as opposed to the polygon itself outlining the desired region.

Hope that makes sense. i.e. Making the overlay fit the bounds of the map sounds like it might be what I am after as well.

**Comment by hansemannn** [comment]
You can calculate the `zoom` based on the latitude, longitude, radius of the overlay. See a native example [here](https://stackoverflow.com/questions/41829163/how-to-fit-bounds-of-gmscircle-with-google-maps-sdk-to-completely-show-on-map). Camera updates and custom location settings are supported here as well, so it's just some calculation.
