### ISSUE TITLE
Half of the README dissappeared in last commit

### ISSUE THREAD

**Issue by MattDelmarter** [hansemannn/titanium-googlemaps#119]
I was looking through the README and wondered why it was missing so much content.

The update on Feb 22nd removed a lot of it - I am guessing by mistake ;)

https://github.com/hansemannn/titanium-googlemaps/commit/22812e9b6a066dcaa17fccaad2a79bfc99c08d06#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by MattDelmarter** [comment]
Also while in there - Clustering is mentioned twice in the list of API's supported :)

- [ ]  Clustering
- [ ]  Directions
- [ ]  Clustering

**Comment by hansemannn** [comment]
I have no idea how that happened, but thanks for the pair of eagle eyes! Can you confirm it's correct now?

**Comment by MattDelmarter** [comment]
Yup perfect 👍
