### ISSUE TITLE
Tiles overlay and hide Polygons - zIndex not honored?

### ISSUE THREAD

**Issue by MattDelmarter** [hansemannn/titanium-googlemaps#120]
I have been experimenting with tiles and it is offers some exciting options. But one issue I have noticed is that it does not matter what zIndex I set for Polygons or the tiles, the tiles always overlay and hide any polygons on the map.

Maybe the polygons are not using the zIndex value?

**Comment by hansemannn** [comment]
The `zIndex` property is not exposed for polyline / polygon and circle overlays so far.

**Comment by hansemannn** [comment]
Added as part of https://github.com/hansemannn/titanium-googlemaps/commit/70d92d5d95821db14faa960c4b1e9c2e9caea761, new release soon.
