### ISSUE TITLE
Click on polygon returns "1" as clicksource

### ISSUE THREAD

**Issue by MattDelmarter** [hansemannn/titanium-googlemaps#122]
When I click on an element on the map the `e.clicksource` is correctly identified as:

1. map
2. pin
3. infoWindow

... but not when clicking on a polygon. The `e.clicksource` in that case is returned as a `1`.

Clicking on a polygon should return a clicksource of `overlay` if I am understanding correctly?

**Comment by hansemannn** [comment]
The `clicksource` returns a constant for overlays, e.g. 
- `GoogleMaps.OVERLAY_TYPE_POLYGON`
- `GoogleMaps.OVERLAY_TYPE_POLYLINE`
- `GoogleMaps.OVERLAY_TYPE_CIRCLE`

That could indeed be described in the readme as well.
