### ISSUE TITLE
Autocomplete Dialog enhance

### ISSUE THREAD

**Issue by julien9999** [hansemannn/titanium-googlemaps#123]
Thanks Hans for this great module.
Is it possible to get the nearest POI from the Dialog by giving it lat-lon ?
and maybe filter by types ?
Thanks

**Comment by Sambusik** [comment]
It’s not part of the google maps SDK, however you can programmatically get the nearest long/lat in an array to another long/lat. there are several js libs that do this.

**Comment by hansemannn** [comment]
Please use the Autocomplete REST API for that. We use it as well and it's working great! If you still need it, you can implement the `autocompleteBounds` property to the `TiGooglemapsAutocompleteDialogProxy` class!

**Comment by hansemannn** [comment]
The `AutocompleteDialog` API was deprecated by Google, so this bridge will not support new features for that specific API anymore.
