### ISSUE TITLE
Some regions are not correctly shown

### ISSUE THREAD

**Issue by AndreaVitale** [hansemannn/titanium-googlemaps#126]
I'm trying to center a map in Rome (41.890096, 12.4901653) but the map is blank.
As you can see in the screencast only a portion of the entire map is shown correctly.
The API is OK, because if I try to use your coords described in the README the map is correctly shown.

![Screencast GIF](https://user-images.githubusercontent.com/2265079/40644202-b823a7f8-6322-11e8-9cb4-28f659edfb5b.gif)

**Comment by hansemannn** [comment]
Looks super weird. I'd actually identify it as a temporary issue in the native iOS SDK, since we do not do anything special in rendering the map.

**Comment by hansemannn** [comment]
I cannot reproduce it with the sample apps attached via `example/`. It has to be either a temporary Google issue or an issue with the api-key. Please re-install the app or reset the Simulator to try it again.
