### ISSUE TITLE
latitude, longitude in "regionchanged" event are wrong

### ISSUE THREAD

**Issue by LilianAlvarez** [hansemannn/titanium-googlemaps#129]
Since the version 3.13.0 and up until the last one, the latitude, and longitude returns by region changed event or directly from map.region.latitude, is the left top latitude corner. 
I was not able to see where the problem came from in the code but still i did experience it.

**Comment by hansemannn** [comment]
I just updated the module to the next major (4.0.0) which has one breaking change that is about selecting annotations: When you select an annotation, the map used to center itself with the new annotation region. Now, that is up to the developer to achieve parity with Ti.Map / Android. Give it a try!

**Comment by LilianAlvarez** [comment]
Hello @hansemannn ,

First, thanks for the quick answer and the update. I just tried it and the map.location do not return anything it's always null. The map 'regionchanged' event still return the top left corner position instead of the center of the map. When i click on an annotation, the annotation do not get the click event like he use to (i did setup touchEnabled : true).
So the problem still remains

**Comment by hansemannn** [comment]
I double checked the value and that changed was a GoogleMaps update. In that case, it seems like either a native issue or expected behavior by the native SDK. Please file an issue at Google if you still want to track this.
