### ISSUE TITLE
Callout or infoWindow not showing on annotation click

### ISSUE THREAD

**Issue by Brianggalvez** [hansemannn/titanium-googlemaps#130]
With last release and running the example, clicking the annotion fires a click event but neither the callout nor the infoWindow is displayed.

**Comment by hansemannn** [comment]
This may have been caused by https://github.com/hansemannn/titanium-googlemaps/commit/647a4b12f013bd8d0092c0ea86c87d9695984f16, can you verify?

**Comment by Brianggalvez** [comment]
just tested with last release and the example provided, and the click event is fired but no callout is showing

**Comment by hansemannn** [comment]
Please read the previous comment again :-) I asked you to check if a recent commit caused the issue, so if you could revert it locally and check if it makes a difference.

**Comment by Brianggalvez** [comment]
Sorry for late response, just tested reverting the commit you suggested and the result is the same, I can see the click event fired buy any callout or infoWindow is displayed

**Comment by pebosi** [comment]
i can confirm this issue, no infoWindow is opened. Any chance to trigger it manually?

**Comment by hansemannn** [comment]
I just had some time to verify this. You have to explicitly call `mapView.selectAnnotation(annotation)` to show the  info window properly. See a native example and discussion around this [here](https://stackoverflow.com/a/19285572/5537752).
