### ISSUE TITLE
Compilation error with the latest version.

### ISSUE THREAD

**Issue by LilianAlvarez** [hansemannn/titanium-googlemaps#133]
I tried to compile the latest version of Google Maps : 4.2.0 and got this error :
[ERROR]  ** BUILD FAILED **
[ERROR]  The following build commands failed:
[ERROR]  	Ld /Users/admin/Desktop/Zone\ de\ chasse/zoneDeChasse/build/iphone/build/Products/Debug-iphonesimulator/zone\ de\ chasse.app/zone\ de\ chasse normal x86_64
[ERROR]  (1 failure)
Build failed. Process exited with code 1.

**Comment by dkjeune** [comment]
good morning, same problem for me.

**Comment by hansemannn** [comment]
Can you paste the full trace log?

**Comment by dkjeune** [comment]
i have this:

[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/noureddine/Documents/Appcelerator_Studio_Workspace/APPLI\ Live/build/iphone/build/Products/Debug-iphonesimulator/APPLI\ Live.app/APPLI\ Live normal x86_64
[ERROR] (1 failure)

**Comment by hansemannn** [comment]
Can you please read my comment more carefully?

**Comment by dkjeune** [comment]
[trace.txt](https://github.com/hansemannn/titanium-googlemaps/files/2996500/trace.txt)

**Comment by hansemannn** [comment]
It seems like Google increased the minimum iOS version to 9.0, so you need to specify that in your tiapp.xml

**Comment by dkjeune** [comment]
It work !
Thanks for your help.
