### ISSUE TITLE
Error on Annotation Click Event

### ISSUE THREAD

**Issue by dkjeune** [hansemannn/titanium-googlemaps#134]
Good morning,

I have an error sometimes on click event when I try to get userData of an Annotation :
 **"undefined is not an object (evaluating 'e.annotation.userData')";**

mapview.addEventListener('click',function(e){
	alert(e.annotation.userData);	
});

Can you check this point ?
Thanks for help.

**Comment by hansemannn** [comment]
Works fine here. Make sure the `userData` is a dictionary that is set on creation of the annotation and make sure the `clicksource` is  `annotation`.

**Comment by dkjeune** [comment]
This error appear after an updateLocation of the annotation.

When I try to get the clicksource, I don't have 'annotation', I have 'pin'
mapview.addEventListener('click',function(e){
  alert(e.clicksource);
});
