### ISSUE TITLE
Polygon holes not works.

### ISSUE THREAD

**Issue by yuranevmer** [hansemannn/titanium-googlemaps#137]
Hi.
Polygon 'holes' property not works as expected;
Here is my example polygon:
```
$.mapView.add(maps.createPolygon({
    "points": [
        [30, 49],
        [30, 50],
        [31, 50],
        [31, 49],
        [30, 49]
    ],
    "fillColor": "#7fff0000",
    "holes": [
        [30.5, 49.5],
        [30.5, 49.7],
        [30.7, 49.7],
        [30.7, 49.5],
        [30.5, 49.5]
    ],
    "zIndex": 10
}))
```
Screenshot from app:
![App](https://user-images.githubusercontent.com/1327542/67678411-30731a00-f98f-11e9-9a46-fd4fc30b504a.png)
Screenshot from geojson.io:
![geojson.io](https://user-images.githubusercontent.com/1327542/67678509-6f08d480-f98f-11e9-9c8e-839d3eca268b.png)

iOS 13.1, Ti.SDK 8.2.0.GA.

**Comment by hansemannn** [comment]
The holes have the indices swapped, e.g. latitude at index 1 and longitude at index 0. I just fixed that in v6.1.2!
