### ISSUE TITLE
Click on pin doesn't show info window

### ISSUE THREAD

**Issue by Max87ZA** [hansemannn/titanium-googlemaps#139]
Hello guys, I implemented code from example and added annotations into mapView. When I click on annotation, it should show info window but it doesn't. Is this a bug or do I need something to set up?
Thanks

**Comment by Sambusik** [comment]
Yep same here. Annotation Click nor Polygons being drawn. 
This occurs on Ti SDK 9.2.x+ and even with older ti.googlemaps modules. 

The odd things is that it seems the issue is from Ti 9.2.0 since the same module worked for Annotation click/Polygons in Ti SDK 8.x.x

**Comment by yozef** [comment]
Yep same here. Annotation Click nor Polygons being drawn.
This occurs on Ti SDK 9.2.x+ and even with older ti.googlemaps modules.

The odd things is that it seems the issue is from Ti 9.2.0 since the same module worked for Annotation click/Polygons in Ti SDK 8.x.x

**Comment by hansemannn** [comment]
@yozef Your issue sounds very different. And please compare the exact versions of the module to see if it's really an SDK- or module issue.

@Max87ZA I will look into this, sorry for the delay!
