### ISSUE TITLE
setting scrollGesture = false isn't working

### ISSUE THREAD

**Issue by grantges** [hansemannn/titanium-googlemaps#142]
Per the documentation, you can enable / disable scrolling by setting the `scrollGesture` property:

I'm looking to prevent the user enabled ability to scroll by doing the following.

`mapview.scrollGesture = false;`

However, even with the property set, the user is able to move the map around which isn't the desired behavior.

**Comment by grantges** [comment]
Looking through the code, it looks like the function for this is available - but not the property as referenced here: 

https://github.com/hansemannn/titanium-googlemaps#enable--disable-gestures


Work around for now is to use the function `mapview.setScrollGestures(false)` for now.

**Comment by grantges** [comment]
after more investigation this seems to be caused by not specifying the version of the module - it was picking up an older version vs the latest (6.1.0) that I had installed. Forcing version addressed the issue. closing the bug.

**Comment by hansemannn** [comment]
Cool!
