### ISSUE TITLE
Issue with GoogleMaps. bundle

### ISSUE THREAD

**Issue by macasfaj** [hansemannn/titanium-googlemaps#145]
I'm upgrading my App to SDK10.1.1GA and using 7.0.0 module version and do this:

`var maps = require("ti.googlemaps");

  maps.setAPIKey(Alloy.CFG['iOSKey' + Alloy.Globals.selMun]);
  var mapa = maps.createView({
    mapType : maps.MAP_TYPE_NORMAL,
    top : 0,
    width : Ti.UI.FILL,
    height : Ti.UI.FILL,
    userLocation : false,
    zIndex : 0,
    region : {
      // Camera center of the map
      latitude : 36.7292583,
      longitude : -4.4108482,
      zoom : 16 // Zoom in points
    }
  });`

But I get this error:

`[ERROR]     var mapa = maps.createView({
[ERROR]                                ^
[ERROR] : Google Maps SDK for iOS requires GoogleMaps.bundle to be part of your target under 'Copy Bundle Resources'
[ERROR]     at  ([native code])
[ERROR]     at Controller (/alloy/controllers/ventanaMapa.js:196:31)
[ERROR]     at  (/alloy.js:427:53)
[ERROR]     at Controller (/alloy/controllers/info_mapa_itinerario_cofradia.js:283:41)
[ERROR]     at  (/alloy.js:427:53)
[ERROR]     at openWin (/alloy/controllers/index.js:195:27)
[ERROR]     at  (/alloy/controllers/cofradias.js:334:26)
[ERROR]   
`

Any idea????

**Comment by hansemannn** [comment]
And this was no issue with previous versions?

**Comment by macasfaj** [comment]
6.2.0 works fine, I'm testing right now

**Comment by yozef** [comment]
Hi @macasfaj :)

What I've noticed, when I pull my Project from Repo where the module has been pushed there, it dosen't seem to store large files. The work around for me was to re-add it to your local project from the releases: https://github.com/hansemannn/titanium-googlemaps/releases/tag/v7.0.0

**Comment by hansemannn** [comment]
Ah, yeah, you need git-lfs. Usually make sure to use the releases instead, yep!
