### ISSUE TITLE
App randomly crashing on iOS 15.4 Simulator (Xcode 13.3+)

### ISSUE THREAD

**Issue by hansemannn** [hansemannn/titanium-googlemaps#148]
If you are experiencing this - no worries! It only happens on Simulator devices and only on the iOS 15.4 ones (bundled with Xcode 13.3). There is a discussion over at the RN binding as well: https://github.com/react-native-maps/react-native-maps/issues/4130. You can also find the issue on the Google issue tracker: https://issuetracker.google.com/issues/224584852

**Comment by nelsonprsousa** [comment]
Looks like it is fixed with v1.1.0.

We can close this issue @hansemannn

**Comment by hansemannn** [comment]
@nelsonprsousa This is not the react-native-maps repo, I was just referencing the error :) But I will definitely validate the native SDK upgrade here as well, thank you!

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa This is not the react-native-maps repo, I was just referencing the error :) But I will definitely validate the native SDK upgrade here as well, thank you!

N00b me got lost on multiple tabs. I am sorry.

Anyway, I can let you know that the binding with the SDK upgrade worked for me and the crash no longer happens.

Sorry about the mess
